name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  # dummy database url for build time --> prisma
  DATABASE_URL: file:./dev.db

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack/pnpm
        run: |
          corepack enable
          corepack pnpm --version

      - name: Install dependencies for backend
        run: corepack pnpm install --frozen-lockfile && corepack pnpm run prisma-generate

      - name: Run tests for backend
        run: corepack pnpm test

  build-amd64:
    runs-on: self-hosted
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4


      - name: Build Docker Image (amd64)
        uses: docker/build-push-action@v7
        with:
          context: ./
          push: false
          platforms: linux/amd64
          build-args: |
            VERSION_ARG=${{ github.ref_name }}
          tags: |
            quickstack/quickstack:test-amd64